define({
	root: {
		id: "Id",
		requestType: "Request Type",
		description: "Description",
		status: "Status",
		priority: "Priority",
		requestedBy: "Requested By",
		requestedFinishDate: "Requested Finish Date",
		requestedFinishFromDate: "From Date",
		requestedFinishToDate: "To Date",
		requestedFinishFromToDate: "Requested Finish From/To Date",
		assignedTo: "Assigned To",
		actualFinishDate: "Actual Finish Date",
		estimatedUnits: "Estimated Units",
		unitType: "Unit Type",
		createdDate: "Created Date",
		submitSearch: "Submit Search",
		updatedDate: "Updated Date",
		home: "Home",
		work: "Work",
		cell: "Cell",
		name: "Name",
		first: "Firstname",
		last: "Lastname",
		company: "Company",
		searchTitle: "Search/Sort",
		search: "Search",
		sort: "Sort",
		firstSort: "1st",
		secondSort: "2nd",
		mail: "E-mail",
		phone: "Phone",
		cancel: "Cancel",
		ok: "Ok",
		remove: "Delete"
	}
});